# Generated by Django 6.0.7 on 2026-08-11 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpl', '0001_initial'),
        ('leagues', '0003_leaguemember'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_points', models.IntegerField(help_text='Official FPL points for this gameweek, chip effects included.')),
                ('chip_used', models.CharField(blank=True, choices=[('bboost', 'Bench Boost'), ('3xc', 'Triple Captain'), ('wildcard', 'Wildcard'), ('freehit', 'Free Hit')], max_length=10, null=True)),
                ('adjusted_points', models.IntegerField(help_text='raw_points with bench boost / triple captain bonus removed. Equal to raw_points if no scoring chip was used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_scores', to='fpl.gameweek')),
                ('league_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_scores', to='leagues.leaguemember')),
            ],
            options={
                'verbose_name': 'Weekly Score',
                'verbose_name_plural': 'Weekly Scores',
                'ordering': ['gameweek', 'league_member'],
                'constraints': [models.UniqueConstraint(fields=('league_member', 'gameweek'), name='unique_weeklyscore_per_member_per_gw')],
            },
        ),
    ]
