# Generated by Django 6.0.7 on 2026-08-11 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpl', '0002_weeklyscore'),
        ('leagues', '0003_leaguemember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(help_text="Cumulative points for this member from the league's start_gameweek through this gameweek.")),
                ('rank', models.PositiveSmallIntegerField(help_text="Member's rank within the league as of this gameweek.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='fpl.gameweek')),
                ('league_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='leagues.leaguemember')),
            ],
            options={
                'verbose_name': 'Standing',
                'verbose_name_plural': 'Standings',
                'ordering': ['gameweek', 'rank'],
                'constraints': [models.UniqueConstraint(fields=('league_member', 'gameweek'), name='unique_standing_per_member_per_gw')],
            },
        ),
    ]
