# Generated by Django 6.0.7 on 2026-08-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fpl_manager_name',
            field=models.CharField(blank=True, help_text='Manager name as registered on the official FPL platform.', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='fpl_team_name',
            field=models.CharField(blank=True, help_text='FPL team name as registered on the official FPL platform.', max_length=100),
        ),
    ]
