# Generated by Django 6.0.7 on 2026-08-06 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['-created_at'], 'verbose_name': 'League', 'verbose_name_plural': 'Leagues'},
        ),
        migrations.AlterField(
            model_name='league',
            name='include_chip_points',
            field=models.BooleanField(default=False, help_text='Include chip bonus points when calculating standings.'),
        ),
        migrations.AlterField(
            model_name='league',
            name='start_gameweek',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(38)]),
        ),
        migrations.AlterField(
            model_name='league',
            name='total_gameweeks',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(38)]),
        ),
    ]
